language: node_js

node_js: node

branches:
  only:
    - hexo
    
notifications:
  email:
    recipients:
      - hiyforever@126.com
    on_success: always
    on_failure: always

cache:
  directories:
    - node_modules

script:
  - hexo g

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: hexo
    
