language: node_js

branches:
  only:
    - hexo

before_install:
  - git config --global user.name 'miku'
  - git config --global user.email miku@miku.tk

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g -d