language: node_js

node_js:
  - 6.2.0

branches:
  only:
    - hexo

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: hexo