language: node_js

branches:
  only:
    - hexo

cache:
  yarn: true
  directories:
    - node_modules

script:
  - hexo g

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: hexo